### ISSUE TITLE
Убрать аннотации @Component

### ISSUE THREAD

**Issue by arsen-sepikhanov** [gramant/auth-starter#6]
Если я правильно понимаю, то поскольку пользователи библиотеки не включают компонент-скан по пакету библиотеки, то эта и ее поданнотации бессмысленны. А если все таки включат, то в контексте будет два бина одного типа, один от аннотации, а второй созданный вручную в AuthConfig, что приведет к падению при первой возможности

**Comment by gilinykh** [comment]
убрал `@Service`, `@Repository`, `@RestController` аннотации
